package com.diancanw.model;

// Generated 2012-2-14 22:19:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import android.R.raw;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {
	private Integer id;
	private String name;
	private String image;
	private String description;

	public Category() {
	}

	public Category(String name) {
		this.name = name;
	}

	public Category(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
