package com.diancanw.model;


// Generated 2012-2-14 22:19:35 by Hibernate Tools 3.4.0.CR1

/**
 * Table generated by hbm2java
 */
public class Desk implements java.io.Serializable {
	private Integer id;
	private String  name;
	private String  description;
	private Integer capacity;
	private Integer orderStatus;
	private Integer tid;
	private int wid;
	private String  code;
	private Integer oid;


	public Integer getOid() {
		return oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Desk() {
	}

	public Desk(String name, String description, Integer capacity) {
		this.name = name;
		this.description = description;
		this.capacity = capacity;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTid() {
		return tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	public int getWid() {
		return wid;
	}

	public void setWid(int wid) {
		this.wid = wid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	public Integer getOrderStatus() {
		return orderStatus;
	}

	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}

	
}
