package com.modelw;


// Generated 2012-2-14 22:19:35 by Hibernate Tools 3.4.0.CR1

/**
 * Table generated by hbm2java
 */
public class Desk implements java.io.Serializable {
	private Integer id;
	private String name;
	private String description;
	private Integer capacity;
	private Integer status;
	private Integer tid;
	private String code;


	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Desk() {
	}

	public Desk(String name, String description, Integer capacity) {
		this.name = name;
		this.description = description;
		this.capacity = capacity;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTid() {
		return tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
}
