package com.modelw;

import android.R.integer;

// Generated 2012-2-14 22:19:35 by Hibernate Tools 3.4.0.CR1

/**
 * Recipe generated by hbm2java
 */
public class Recipe implements java.io.Serializable {
	private Integer id;
	private Integer cid;
	private String name;
	private String description;
	private String image;
	private String cname;
	private Integer price;

	public Recipe() {
	}

	public Recipe(Integer cid, String name, String description,
			String image, Integer price) {
		this.cid = cid;
		this.name = name;
		this.description = description;
		this.image = image;
		this.price = price;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getImage() {
		return this.image;
	}

	public String getCname() {
		return cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

}
